service:
    host: "127.0.0.1"
    port: 4000
    rest_root_path: "/v1/adtg"
    flask_debug_mode: false
    
    enable_oidc: false
    secrets_json_path: "./secret.json"
    check_user_token: false
    apply_user_token: false
    
compiler:
    idt_jinja_tmpl: "path"
    mdt_jinja_tmpl: "path"
    algodt_jinja_tmpl: "path"

logging:
    version: 1
    root:
        level: DEBUG
        handlers: [console, file]
    formatters:
        simpleFormatter:
            #format: "%(module)s %(asctime)s %(levelname)s %(message)s"
            format: "%(asctime)s %(levelname)s %(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormatter
            level: DEBUG
            stream: ext://sys.stdout
        file:
            class : logging.FileHandler
            formatter: simpleFormatter
            mode: w
            level: DEBUG
            filename: record.log
    loggers:
        adtg_api:
            propagate: false
            handlers: [console, file]
        adtg_compiler:
            propagate: false
            handlers: [console, file]
