service:
    host: "127.0.0.1"
    port: 4000
    rest_root_path: "/v1/adtg"
    flask_debug_mode: True
    working_directory: "/home/ubuntu/github-adtg/examples"
    public_endpoint: "http://127.0.0.1:4000"

    enable_oidc: false
    secrets_json_path: "/home/ubuntu/github-adtg/config/secret.json"
    check_user_token: false
    apply_user_token: false
    
compiler:
    template_directory: "/home/ubuntu/github-adtg/compiler/templates"
    templates:
        ddt: "ddt.yaml"
        mdt: "mdt.yaml"
        algodt: "algodt.yaml"
    modules:
        translator:
            import: 'from compiler.utils import translator'
            functions:
                - translate
            

logging:
    version: 1
    root:
        level: DEBUG
        handlers: [console, file]
    formatters:
        simpleFormatter:
            format: "%(module)s %(asctime)s %(levelname)s %(message)s"
            #format: "%(asctime)s %(levelname)s %(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormatter
            level: DEBUG
            stream: ext://sys.stdout
        file:
            class : logging.FileHandler
            formatter: simpleFormatter
            mode: w
            level: DEBUG
            filename: record.log
    loggers:
        adtg:
            propagate: false
            handlers: [console, file]
        adtg_compiler:
            propagate: false
            handlers: [console, file]
