# Debugger configs file. If not exists debugger applies default values.
# You can comment any of the configs and default will be applied
debugger:
  # Set path to debugger logs
  path: '/Users/dimitriskagialis/adt_generator/'
  # Set debugger logs folder
  folder: 'debugger-1'
  # Set debugging level [allowed values 'low','high','full']
  level: 'high'
  # Set debugging scope - can be packages, modules, functions [if not defined debugger will debug the whole project]
  packages:
    # Package name
    tests:
      # Module name
      test_adt_generator:
        # Functions
#       #- subadd
        - subsubadd
    # module
    __main__:


