logger:
  # Set path to logs
  path: '/Users/dimitriskagialis/adt_generator/'
  # Set logs folder
  folder: 'logs-1'
  # Set logging level [allowed values 'info' or 'warning']
  level: 'info'
  # Set logging handler [allowed values 'file' or 'screen']
  handler: 'file'

  # TODO: check standard config for the logger